# development docker-compose file
version: '2.1'

services:

  scraper:
    image: unocha/hdx-scraper-wfp-foodprices:1.0
    volumes:
      - "./:/srv"
    working_dir: /srv
    command: sh ./run-dev.sh
    env_file:
      - run_env
